name: CodeCov

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Generate Report
        run: |
          pip install coverage pytest
          coverage run -m pytest
          coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
